import Head from "next/head";
import dynamic from "next/dynamic";
import Navbar from "../components/sections/Navbar";
import Hero from "../components/sections/Hero";
import About from "../components/sections/About";
import Skills from "@/components/sections/Services";
import Layout from "@/components/Layout";

const Blob = dynamic(() => import("../components/Blob"));

export default function Home() {
  return (
    <>
      <Head>
        <title>Maciek</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
      <Blob />
      <Hero />
      <Skills />
      <About />
    </>
  );
}
